#!/usr/bin/env python
from misc.utility.scons_hints import *

import platform

Import("env")

try:
    if platform.system() == "Linux":
        openssl_include_path = "/usr/include/openssl"  # Generic location for Linux.
        env.Append(LIBS=["ssl", "crypto"])
    elif platform.system() == "OpenBSD":
        openssl_include_path = "/usr/include/openssl"  # Generic OpenBSD location
        env.Append(["ssl", "crypto"])
    elif platform.system() == "FreeBSD":
        openssl_include_path = "/usr/local/include/openssl"  # Generic FreeBSD location
    elif platform.system() == "Darwin":
        openssl_include_path = "/usr/local/opt/openssl/include"  # Generic location for MacOS?
        env.Append(LIBS=["ssl", "crypto"])
    elif platform.system() == "Windows":
        openssl_include_path = "C:/OpenSSL/include"  # Generic location for Windows?
        env.Append(IBS=["libssl.lib", "libcrypto.lib"])
    else:
        print("I don't work on your machine.")

    env.Append(CPPATH=[openssl_include_path])
    env.add_source_files(env.modules_sources, "*.cpp")  # Add all cpp files to the build
except ImportError:
    pass
